version: '3.8'

services:
  # Frontend service (Next.js)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - frontend_node_modules:/app/frontend/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend
    networks:
      - cv-analyzer-network

  # Backend service (FastAPI)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app/backend
      - backend_pip_cache:/root/.cache/pip
    environment:
      - PYTHONPATH=/app/backend
      - PORT=4000
    networks:
      - cv-analyzer-network

  # Nginx proxy (production-like setup)
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - cv-analyzer-network

networks:
  cv-analyzer-network:
    driver: bridge

volumes:
  frontend_node_modules:
  backend_pip_cache:
